controller_names:
  - manipulator_joint_trajectory_controller

manipulator_joint_trajectory_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - joint12
    - joint23
    - joint34
    - joint45
    - joint56