controller_list:
  - name: fake_moveit_arm_controller_controller
    type: $(arg execution_type)
    joints:
      - joint12
      - joint23
      - joint34
      - joint45
      - joint56
  - name: fake_gripper_controller_controller
    type: $(arg execution_type)
    joints:
      - joint56
      - grabber_joint1
      - grabber_joint2
initial:  # Define initial robot poses.
  - group: moveit_arm_controller
    pose: Home