# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: moveit_arm_controller
  joint_model_group_pose: Home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - arm_back_joint
    - drum_back_joint
    - joint12
    - joint23
    - joint34
    - joint45
    - joint56
    - grabber_joint1
    - grabber_joint2
    - left_wheel_back_joint
    - left_wheel_front_joint
    - right_wheel_back_joint
    - right_wheel_front_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: partial_autonomy_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - joint12
      - joint23
      - joint34
      - joint45
      - joint56

#moveit_arm_controller_controller:
#  type: position_controllers/JointTrajectoryController
#  joints:
#    - joint12
#    - joint23
#    - joint34
#    - joint45
#    - joint56
#  gains:
#    joint12:
#      p: 100
#      d: 1
#      i: 1
#      i_clamp: 1
#    joint23:
#      p: 100
#      d: 1
#      i: 1
#      i_clamp: 1
#    joint34:
#      p: 100
#      d: 1
#      i: 1
#      i_clamp: 1
#    joint45:
#      p: 100
#      d: 1
#      i: 1
#      i_clamp: 1
#    joint56:
#      p: 100
#      d: 1
#      i: 1
#      i_clamp: 1
