# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: moveit_arm_controller
  joint_model_group_pose: Home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    # - arm_back_hinge
    # - drum_back_hinge
    - joint12
    - joint23
    - joint34
    - joint45
    - joint56
    # - grabber_joint1
    # - grabber_joint2
    # - left_wheel_back_hinge
    # - left_wheel_front_hinge
    # - right_wheel_back_hinge
    # - right_wheel_front_hinge
  sim_control_mode: 1  # 0: position, 1: velocity

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 5000

controller_names:
  - joint_trajectory_controller

joint_trajectory_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - joint12
    - joint23
    - joint34
    - joint45
    - joint56