name: Build
on:
  pull_request:
    branches:
      - development
  push:
    branches:
      - development

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Pull repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install linting tools
        run: python -m pip install --upgrade pip black flake8

      - name: Check Black formatting
        run: python -m black --check .

      - name: Check PEP8 compliance
        run: python -m flake8 .